# Generated by Django 5.1.7 on 2025-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Range Rover', 'Range Rover'), ('Toyota', 'Toyota'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault')], max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par jour ($)')),
                ('prix_mois', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par mois ($)')),
                ('image', models.ImageField(upload_to='voitures/', verbose_name='Image de la voiture')),
            ],
        ),
    ]
