# Generated by Django 5.1.7 on 2025-03-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_alter_voiture_image_alter_voiture_prix_jour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.voiture')),
            ],
        ),
    ]
