# Generated by Django 5.1.7 on 2025-03-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offres/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
