# Generated by Django 5.1.4 on 2025-03-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0006_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
