# Generated by Django 4.2.20 on 2025-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_promotionslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='marque',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Range Rover', 'Range Rover'), ('Toyota', 'Toyota'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Nissan', 'Nissan'), ('Kia', 'Kia'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Fiat', 'Fiat'), ('Citroën', 'Citroën'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Volvo', 'Volvo'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Dacia', 'Dacia'), ('Jeep', 'Jeep'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Ram', 'Ram'), ('Alfa Romeo', 'Alfa Romeo'), ('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Maserati', 'Maserati'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Bugatti', 'Bugatti'), ('Tesla', 'Tesla'), ('Skoda', 'Skoda'), ('Seat', 'Seat'), ('Mini', 'Mini'), ('Aston Martin', 'Aston Martin'), ('Infiniti', 'Infiniti'), ('Acura', 'Acura'), ('Genesis', 'Genesis'), ('Saab', 'Saab'), ('Hummer', 'Hummer'), ('Lincoln', 'Lincoln'), ('Cadillac', 'Cadillac'), ('GMC', 'GMC'), ('Chery', 'Chery'), ('Geely', 'Geely'), ('BYD', 'BYD'), ('Great Wall', 'Great Wall'), ('Mahindra', 'Mahindra'), ('Tata', 'Tata'), ('Proton', 'Proton'), ('Perodua', 'Perodua'), ('SsangYong', 'SsangYong'), ('Isuzu', 'Isuzu'), ('Scania', 'Scania'), ('MAN', 'MAN')], max_length=50, verbose_name='Marque'),
        ),
    ]
